require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BansController do

  # This should return the minimal set of attributes required to create a valid
  # Ban. As you add validations to Ban, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bans as @bans" do
      ban = Ban.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bans).should eq([ban])
    end
  end

  describe "GET show" do
    it "assigns the requested ban as @ban" do
      ban = Ban.create! valid_attributes
      get :show, {:id => ban.to_param}, valid_session
      assigns(:ban).should eq(ban)
    end
  end

  describe "GET new" do
    it "assigns a new ban as @ban" do
      get :new, {}, valid_session
      assigns(:ban).should be_a_new(Ban)
    end
  end

  describe "GET edit" do
    it "assigns the requested ban as @ban" do
      ban = Ban.create! valid_attributes
      get :edit, {:id => ban.to_param}, valid_session
      assigns(:ban).should eq(ban)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ban" do
        expect {
          post :create, {:ban => valid_attributes}, valid_session
        }.to change(Ban, :count).by(1)
      end

      it "assigns a newly created ban as @ban" do
        post :create, {:ban => valid_attributes}, valid_session
        assigns(:ban).should be_a(Ban)
        assigns(:ban).should be_persisted
      end

      it "redirects to the created ban" do
        post :create, {:ban => valid_attributes}, valid_session
        response.should redirect_to(Ban.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ban as @ban" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ban.any_instance.stub(:save).and_return(false)
        post :create, {:ban => {}}, valid_session
        assigns(:ban).should be_a_new(Ban)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ban.any_instance.stub(:save).and_return(false)
        post :create, {:ban => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ban" do
        ban = Ban.create! valid_attributes
        # Assuming there are no other bans in the database, this
        # specifies that the Ban created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ban.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ban.to_param, :ban => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ban as @ban" do
        ban = Ban.create! valid_attributes
        put :update, {:id => ban.to_param, :ban => valid_attributes}, valid_session
        assigns(:ban).should eq(ban)
      end

      it "redirects to the ban" do
        ban = Ban.create! valid_attributes
        put :update, {:id => ban.to_param, :ban => valid_attributes}, valid_session
        response.should redirect_to(ban)
      end
    end

    describe "with invalid params" do
      it "assigns the ban as @ban" do
        ban = Ban.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ban.any_instance.stub(:save).and_return(false)
        put :update, {:id => ban.to_param, :ban => {}}, valid_session
        assigns(:ban).should eq(ban)
      end

      it "re-renders the 'edit' template" do
        ban = Ban.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ban.any_instance.stub(:save).and_return(false)
        put :update, {:id => ban.to_param, :ban => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ban" do
      ban = Ban.create! valid_attributes
      expect {
        delete :destroy, {:id => ban.to_param}, valid_session
      }.to change(Ban, :count).by(-1)
    end

    it "redirects to the bans list" do
      ban = Ban.create! valid_attributes
      delete :destroy, {:id => ban.to_param}, valid_session
      response.should redirect_to(bans_url)
    end
  end

end
